//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     To add or remove a member, edit the .resx file and rerun ResGen,
//     or rebuild the project to regenerate this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitSpeckleExporter
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RevitSpeckleExporterResources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RevitSpeckleExporterResources() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new global::System.Resources.ResourceManager(
                        "RevitSpeckleExporter.RevitSpeckleExporterResources",
                        typeof(RevitSpeckleExporterResources).Assembly);
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static System.Drawing.Bitmap ExportToSpeckle
        {
            get
            {
                return (System.Drawing.Bitmap)ResourceManager.GetObject("ExportToSpeckle", resourceCulture);
            }
        }
    }
}
